import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import PDFDocument = require('pdfkit');
import * as path from 'path';

@Injectable()
export class PdfGeneratorService {
  constructor(private readonly prisma: PrismaService) {}

  async generatePdf(interactionId: string, userId: string): Promise<PDFKit.PDFDocument> {
    const interaction = await this.prisma.aiInteraction.findFirst({
      where: {
        id: interactionId,
        userId: userId,
      },
      include: {
        user: true,
      },
    });

    if (!interaction) {
      throw new NotFoundException('AI Interaction not found or you do not have permission to access it.');
    }

    const doc = new PDFDocument({ margin: 50 });

    const fontPath = path.join(process.cwd(), 'assets', 'fonts', 'Kalpurush.ttf');
    doc.registerFont('BanglaFont', fontPath);

    // Header
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('Study Assistant Report', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('gray')
      .text(`Generated for: ${interaction.user.firstName} ${interaction.user.lastName}`, { align: 'center' })
      .text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' })
      .moveDown(2);

    doc
      .moveTo(50, doc.y)
      .lineTo(550, doc.y)
      .strokeColor('#cccccc')
      .stroke()
      .moveDown(1);

    // AI Prompt / Title
    doc.fillColor('black');
    if (interaction.prompt) {
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('Your Prompt / Question:')
        .moveDown(0.5);

      doc
        .fontSize(12)
        .font('BanglaFont')
        .text(interaction.prompt)
        .moveDown(1.5);
    }

    // AI Response Body
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('AI Response:')
      .moveDown(0.5);

    const sanitizedResponse = interaction.aiResponse.replace(/\*\*/g, '');

    doc
      .fontSize(12)
      .font('BanglaFont')
      .text(sanitizedResponse, {
        align: 'justify',
        lineGap: 2,
      })
      .moveDown(2);

    // Footer
    const bottomY = doc.page.height - 50;
    doc
      .fontSize(10)
      .fillColor('gray')
      .text('Generated by AI Study Assistant', 50, bottomY, {
        align: 'center',
        width: doc.page.width - 100,
      });

    return doc;
  }
}
